INSERT INTO `#__re_amenities` (`id`, `title`, `cat`, `params`) VALUES
(1, 'Tennis Court', 2, NULL),
(3, 'Swimming Pool', 2, NULL),
(4, 'Garage', 2, NULL),
(5, 'Fireplace', 0, NULL),
(6, 'Dishwasher', 1, NULL),
(7, 'Garbage Disposal', 1, NULL),
(8, 'Central Air', 0, NULL),
(9, 'Carpet Throughout', 0, NULL),
(10, 'Washer/Dryer', 1, NULL),
(11, 'Gas Fireplace', 1, NULL),
(12, 'Gas Stove', 0, NULL),
(13, 'Cable TV', 0, NULL),
(14, 'Cable Internet', 0, NULL),
(15, 'Wood Stove', 1, NULL),
(16, 'Jacuzi Tub', 1, NULL),
(17, 'Skylights', 0, NULL),
(18, 'Burglar Alarm', 0, NULL),
(19, 'Handicap Facilities', 1, NULL),
(20, 'Pellet Stove', 1, NULL),
(21, 'Central Vac', 0, NULL),
(22, 'Lawn', 2, NULL),
(23, 'Landscaping', 2, NULL),
(24, 'Open Deck', 2, NULL),
(25, 'Fence', 2, NULL),
(26, 'RV Parking', 2, NULL),
(27, 'Pasture', 2, NULL),
(28, 'Fruit Trees', 2, NULL),
(29, 'Satellite Dish', 0, NULL),
(30, 'Sprinkler System', 2, NULL),
(31, 'Covered Patio', 2, NULL),
(32, 'Boat Slip', 0, NULL),
(33, 'Exterior Lighting', 2, NULL),
(34, 'Spa/Hot Tub', 2, NULL),
(35, 'Gazebo', 2, NULL),
(36, 'Range/Oven', 1, NULL),
(37, 'Refrigerator', 1, NULL),
(39, 'Electric Hot Water', 0, NULL),
(40, 'Microwave', 1, NULL),
(41, 'Washer', 1, NULL),
(42, 'Dryer', 1, NULL),
(43, 'Water Softener', 0, NULL),
(44, 'RO Combo Gas/Electric', 1, NULL),
(45, 'Gas Hot Water', 1, NULL),
(46, 'Propane Hot Water', 0, NULL),
(47, 'Grill Top', 0, NULL),
(48, 'Trash Compactor', 1, NULL),
(49, 'Freezer', 0, NULL);