INSERT INTO `#__re_configs` (`key`, `value`, `params`) VALUES
('accept_term', '1', NULL),
('agent_approved', '1', NULL),
('agent_feat_num', '2', NULL),
('agent_feat_position', '0', NULL),
('agent_image_width', '150', NULL),
('agent_photo_width', '90', NULL),
('agent_rejected', '1', NULL),
('agent_send', '1', NULL),
('agent_show_address', '1', NULL),
('agent_show_contact', '1', NULL),
('agent_show_email', '1', NULL),
('agent_show_fax', '1', NULL),
('agent_show_featured', '1', NULL),
('agent_show_image', '1', NULL),
('agent_show_mobile', '1', NULL),
('agent_show_phone', '1', NULL),
('agent_show_website', '1', NULL),
('agentdetail_contact_form', '1', NULL),
('agentdetail_realties_layout', 'grid', NULL),
('agentdetail_show_address', '1', NULL),
('agentdetail_show_email', '1', NULL),
('agentdetail_show_fax', '1', NULL),
('agentdetail_show_organization', '1', NULL),
('agentdetail_show_phone', '1', NULL),
('agentdetail_show_skype', '1', NULL),
('agentdetail_show_website', '1', NULL),
('agents_layout', 'list', NULL),
('agents_show_email', '1', NULL),
('agents_show_fax', '1', NULL),
('agents_show_phone', '1', NULL),
('agents_show_skype', '1', NULL),
('agents_show_social', '1', NULL),
('article_id', '1', NULL),
('auto_approve', '0', NULL),
('background_color', '#ffe8e8', NULL),
('banner_display', '3', NULL),
('baths_fraction', '0', NULL),
('cat_entries', '1', NULL),
('cat_featured', '1', NULL),
('cat_featured_position', '1', NULL),
('cat_image_width', '90', NULL),
('cat_recursive', '1', NULL),
('com_feat_num', '2', NULL),
('com_feat_position', '0', NULL),
('com_show_address', '1', NULL),
('com_show_contact', '1', NULL),
('com_show_email', '1', NULL),
('com_show_fax', '1', NULL),
('com_show_featured', '1', NULL),
('com_show_image', '1', NULL),
('com_show_phone', '1', NULL),
('com_show_website', '1', NULL),
('comment_components', 'disqus', NULL),
('company_image_width', '150', NULL),
('company_photo_width', '90', NULL),
('crop_resize', '1', NULL),
('currency_digits', '2', NULL),
('date_format', 'Y-m-d', NULL),
('disqus_api', 'Lo2L5SQw3YliLC5BikkvsPjqnrZzG63bhu4fSBY0X5uoRf4QROWM8NIKE3ItbeZX', NULL),
('disqus_language', '', NULL),
('disqus_shortname', 'realestate.disqus.com', NULL),
('email_admin_agent_actived_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello Administrator,\r\nThis is a payment receipt for Invoice {agent_id} sent on {active_date}\r\n\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\nTransaction #: {transaction_id}\r\nStatus: Paid\r\n\r\n\r\nYou may review your agent history at any time by logging in to our website.\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com', NULL),
('email_admin_agent_actived_subject', '{name} just registered for {plan_title} at your site', NULL),
('email_admin_agent_created_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\nHello Administrator\r\n\r\nA customer just place a agent at your site\r\nPlease see bellow for more details about this agent\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\n\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com', NULL),
('email_admin_agent_created_subject', 'New agent placed on your site', NULL),
('email_agent_actived_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello {name},\r\nThis is a payment receipt for Invoice {agent_id} sent on {active_date}\r\n\r\n------------------------------------\r\nTotal: {total_price}\r\n\r\nAmount: {total_price}\r\nTransaction #: {transaction_id}\r\nStatus: Paid\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com', NULL),
('email_agent_actived_subject', 'Invoice Payment Confirmation', NULL),
('email_agent_to_user_body', 'You have a message from email:{email}', NULL),
('email_agent_to_user_subject', 'Agent Message properties', NULL),
('email_approved_body', '', NULL),
('email_approved_subject', '', NULL),
('email_new_property_confirmation_body', 'Dear {customer},\r\nYou have just submitted new property\r\nHere is the details:\r\n{details}\r\nThanks', NULL),
('email_new_property_confirmation_subject', 'You have submitted new property', NULL),
('email_new_property_inform_body', 'Dear Administrator,\r\nUser {customer} has just submitted new property. \r\nProperty details here :\r\n{details}\r\nPlease go this link to see the property details: {link}\r\nThanks', NULL),
('email_new_property_inform_subject', 'New property has been submitted', NULL),
('email_paylater_thanks_body', '', NULL),
('email_paylater_thanks_subject', '', NULL),
('email_rejected_body', '', NULL),
('email_rejected_subject', '', NULL),
('email_request_active_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello {name},\r\n\r\nThank you for purchasing products at our site.\r\nYour payment has been processed successfully, so please login or create an account at the site and visit this link to active your agent\r\nright now {active_link}\r\n\r\n\r\nRegards,\r\nJoomSeller Solutions\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com', NULL),
('email_request_active_subject', 'Please active your agent {agent_id}', NULL),
('email_thanks_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\nHello {name}\r\n\r\nThis is an email confirm that you have placed a agent at joomlaux.com\r\n\r\nThis is detail information for you\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\n\r\n\r\nBest regards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com', NULL),
('email_thanks_subject', 'Thank you for place a agent for JoomlaUX services', NULL),
('email_user_to_agent_body', 'You sent a message to email:{email}', NULL),
('email_user_to_agent_subject', 'User Message properties', NULL),
('enable_capcha', '1', NULL),
('enable_facebookCMT', '1', NULL),
('enable_facebookCMT_agent', '1', NULL),
('enable_facebookCMT_company', '1', NULL),
('enable_facebookCMT_realty', '1', NULL),
('enable_map', '1', NULL),
('enable_recaptcha', '0', NULL),
('facebookAPI', '1436407899917767', NULL),
('featured_accent', '#ff120a', NULL),
('featured_position', '0', NULL),
('file_max_size', '3', NULL),
('form_copyadmin', '0', NULL),
('form_recipient', '0', NULL),
('form_storeforms', '0', NULL),
('gmapapikey', 'AIzaSyC65Cru0kXK7Ftn0C7IA2BZ3UeYO5Y0kGU', NULL),
('image_exts', 'jpg,png', NULL),
('images_zise', '3', NULL),
('imgs_per_row', '20', NULL),
('item_per_page', '3', NULL),
('item_per_row', '1', NULL),
('juxtime', '1435544169', NULL),
('main_img_height', '300', NULL),
('main_img_width', '400', NULL),
('max_desc', '100', NULL),
('max_desc_agents', '200', NULL),
('max_height_image', '600', NULL),
('max_width_image', '450', NULL),
('measurement_units', '0', NULL),
('new_days', '7', NULL),
('new_property_confirmation', '1', NULL),
('new_property_inform', '1', NULL),
('no_images', '3', NULL),
('notify_agent_actived', '1', NULL),
('notify_email', 'email@domain.com', NULL),
('notify_new_agent', '1', NULL),
('num_columns', '1', NULL),
('num_columns_agents', '1', NULL),
('num_columns_realties', '2', NULL),
('num_featured', '5', NULL),
('num_featured_realty', '2', NULL),
('num_hot', '5', NULL),
('num_intro_agents', '1', NULL),
('num_intro_companies', '8', NULL),
('num_intro_realties', '2', NULL),
('num_leading_agents', '0', NULL),
('num_leading_realties', '0', NULL),
('page_cancel_msg', 'Dear Sir! You have cancelled your agent, so please feel free to contact us at contact@joomlaux.com if you need any help. Best Regards!JoomlaUX Customer Services.', NULL),
('page_cancel_title', 'Opp... You have canceled the  agent.', NULL),
('page_cancel_type', '0', NULL),
('page_cancel_url', '', NULL),
('page_thanks_msg', 'Dear Customer! Thank you for submit a agent at our site. Best Regards!JoomlaUX Customer Services.', NULL),
('page_thanks_title', 'Thank you for submit a agent at our site!', NULL),
('page_thanks_type', '1', NULL),
('page_thanks_url', '', NULL),
('private_key', '6LfmWMgSAAAAACimXrxVKEAlvZTdtftklMrF7BIt', NULL),
('public_key', '6LfmWMgSAAAAAJNnMBkKcTnfSoV9kN577ih1yDb4', NULL),
('realties_layout', 'grid', NULL),
('require_login', '0', NULL),
('show_agent', '1', NULL),
('show_featured', '1', NULL),
('show_scats', '1', NULL),
('slide_duration', '3000', NULL),
('social_share', '1', NULL),
('store_email', 'email@domain.com', NULL),
('store_email_name', 'Your Site Administrator', NULL),
('street_num_pos', '0', NULL),
('template', 'default', NULL),
('theme_recaptcha', 'clean', NULL),
('thousand_separator', ',', NULL),
('thumb_img_height', '200', NULL),
('thumb_img_width', '200', NULL),
('updated_days', '7', NULL),
('upload_images', '1', NULL),
('upload_images_per', '1', NULL),
('use_editor', '1', NULL),
('user_access', '3', NULL),
('user_send', '1', NULL);