INSERT INTO `#__re_configs` (`key`, `value`) VALUES
('user_access', '3'),
('template', 'default'),
('auto_approve', '0'),
('use_editor', '1'),
('social_share', '1'),
('accept_term', '1'),
('article_id', '1'),
('date_format', 'Y-m-d'),
('item_per_row', '1'),
('enable_map', '1'),
('upload_images', '1'),
('no_images', '3'),
('imgs_per_row', '3'),
('images_zise', '3'),
('image_exts', 'png,jpg,jpeg'),
('main_img_width', '400'),
('main_img_height', '300'),
('slide_duration', '3000'),
('thumb_img_width', '200'),
('thumb_img_height', '200'),
('store_email', 'email@domain.com'),
('store_email_name', 'Your Site Administrator'),
('notify_email', 'email@domain.com'),
('new_property_inform', '1'),
('new_property_confirmation', '1'),
('agent_approved', '1'),
('agent_rejected', '1'),
('agent_send', '1'),
('user_send', '1'),
('email_new_property_inform_subject', 'New property has been submitted'),
('email_new_property_inform_body', 'Dear Administrator,\r\nUser {customer} has just submitted new property. \r\nProperty details here :\r\n{details}\r\nPlease go this link to see the property details: {link}\r\nThanks'),
('email_new_property_confirmation_subject', 'You have submitted new property'),
('email_new_property_confirmation_body', 'Dear {customer},\r\nYou have just submitted new property\r\nHere is the details:\r\n{details}\r\nThanks'),
('email_approved_subject', ''),
('email_approved_body', ''),
('email_rejected_subject', ''),
('email_rejected_body', ''),
('email_agent_to_user_subject', ''),
('email_agent_to_user_body', ''),
('email_user_to_agent_subject', ''),
('email_user_to_agent_body', ''),
('notify_new_agent', '1'),
('notify_agent_actived', '1'),
('email_thanks_subject', 'Thank you for place a agent for JoomlaUX services'),
('email_thanks_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\nHello {name}\r\n\r\nThis is an email confirm that you have placed a agent at joomlaux.com\r\n\r\nThis is detail information for you\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\n\r\n\r\nBest regards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com'),
('email_request_active_subject', 'Please active your agent {agent_id}'),
('email_request_active_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello {name},\r\n\r\nThank you for purchasing products at our site.\r\nYour payment has been processed successfully, so please login or create an account at the site and visit this link to active your agent\r\nright now {active_link}\r\n\r\n\r\nRegards,\r\nJoomSeller Solutions\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com'),
('email_paylater_thanks_subject', ''),
('email_paylater_thanks_body', ''),
('email_agent_actived_subject', 'Invoice Payment Confirmation'),
('email_agent_actived_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello {name},\r\nThis is a payment receipt for Invoice {agent_id} sent on {active_date}\r\n\r\n------------------------------------\r\nTotal: {total_price}\r\n\r\nAmount: {total_price}\r\nTransaction #: {transaction_id}\r\nStatus: Paid\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com'),
('email_admin_agent_created_subject', 'New agent placed on your site'),
('email_admin_agent_created_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\nHello Administrator\r\n\r\nA customer just place a agent at your site\r\nPlease see bellow for more details about this agent\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\n\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com'),
('email_admin_agent_actived_subject', '{name} just registered for {plan_title} at your site'),
('email_admin_agent_actived_body', 'body,td { font-family: verdana; font-size: 11px; font-weight: normal; }\r\na { color: #0000ff; }\r\n\r\n\r\nHello Administrator,\r\nThis is a payment receipt for Invoice {agent_id} sent on {active_date}\r\n\r\nUser information\r\n{full_info}\r\n\r\n------------------------------------\r\nAmount: {total_price}\r\nTransaction #: {transaction_id}\r\nStatus: Paid\r\n\r\n\r\nYou may review your agent history at any time by logging in to our website.\r\n\r\nRegards,\r\nJoomSeller Solutions\r\n\r\nJoomlaUX - Opensource Solutions.\r\nhttp://www.joomlaux.com'),
('page_thanks_type', '0'),
('page_thanks_url', ''),
('page_thanks_title', 'Thank you for submit a agent at our site!'),
('page_thanks_msg', 'Dear Customer! Thank you for submit a agent at our site. Best Regards!JoomlaUX Customer Services.'),
('page_cancel_type', '0'),
('page_cancel_url', ''),
('page_cancel_title', 'Opp... You have canceled the  agent.'),
('page_cancel_msg', 'Dear Sir! You have cancelled your agent, so please feel free to contact us at contact@joomlaux.com if you need any help. Best Regards!JoomlaUX Customer Services.'),
('enable_recaptcha', '0'),
('public_key', '6LfmWMgSAAAAAJNnMBkKcTnfSoV9kN577ih1yDb4'),
('private_key', '6LfmWMgSAAAAACimXrxVKEAlvZTdtftklMrF7BIt'),
('theme_recaptcha', 'clean'),
('thousand_separator', ','),
('gmapapikey', 'AIzaSyC65Cru0kXK7Ftn0C7IA2BZ3UeYO5Y0kGU'),
('cat_image_width', '90'),
('show_agent', '1'),
('agent_photo_width', '90'),
('agent_show_image', '1'),
('agent_show_address', '1'),
('agent_show_contact', '1'),
('agent_show_email', '1'),
('agent_show_phone', '1'),
('agent_show_mobile', '1'),
('agent_show_fax', '1'),
('agent_show_website', '1'),
('agent_show_featured', '1'),
('agent_feat_num', '2'),
('agent_feat_position', '0'),
('street_num_pos', '0'),
('measurement_units', '0'),
('baths_fraction', '0'),
('new_days', '7'),
('updated_days', '7'),
('banner_display', '3'),
('require_login', '0'),
('company_photo_width', '90'),
('com_show_image', '1'),
('com_show_address', '1'),
('com_show_contact', '1'),
('com_show_email', '1'),
('com_show_phone', '1'),
('com_show_fax', '1'),
('com_show_website', '1'),
('com_show_featured', '0'),
('com_feat_num', '2'),
('com_feat_position', '0'),
('currency_digits', '2'),
('show_featured', '0'),
('featured_position', '0'),
('num_featured', '5'),
('num_hot', '5'),
('num_leading_realties', '0'),
('num_intro_realties', '2'),
('num_columns', '1'),
('max_desc', '100'),
('featured_accent', '#ff120a'),
('form_recipient', '0'),
('form_copyadmin', '0'),
('form_storeforms', '0'),
('num_columns_realties', '2'),
('num_leading_agents', '0'),
('num_intro_agents', '1'),
('num_columns_agents', '1'),
('show_scats', '1'),
('cat_recursive', '1'),
('cat_entries', '1'),
('cat_featured', '1'),
('cat_featured_position', '1'),
('agent_image_width', '150'),
('company_image_width', '150'),
('file_max_size', '3'),
('upload_images_per', '1'),
('background_color', '#ffe8e8'),
('enable_facebookCMT', '1'),
('facebookAPI', '1436407899917767'),
('max_desc_agents', '100'),
('enable_facebookCMT_realty', '1'),
('enable_facebookCMT_agent', '1'),
('enable_facebookCMT_company', '1'),
('num_featured_realty', '2'),
('num_intro_companies', '8');